name: gameplayground
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  csv: ^5.0.0
  share_extend: ^2.0.0
  cupertino_icons: ^0.1.2
  charts_flutter: ^0.9.0
  flame: ^0.29.4
  flutter_blue: ^0.7.2
  intl: ^0.16.1
  path: ^1.6.4
  path_provider: ^2.0.1
  provider: ^4.0.5
  sqflite: ^1.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/levels/
    - assets/audio/background_music.mp3
    - assets/images/backgrounds/ground.png
    - assets/images/backgrounds/sky.png
    - assets/images/birds/bird_dead.png
    - assets/images/birds/bird_wing_down.png
    - assets/images/birds/bird_wing_up.png
    - assets/images/targets/cherry.png
    - assets/images/obstacles/column.png
